---
title: "Index"
author: "Mario"
date: "26/01/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
```

### Number of animals Seen
```{r}
data <- read.csv("data/observations_2022.csv")
head(data)
data %>%
    group_by(RTU) %>% filter(RTU != "none") %>%
    summarise(count=n())
```
### Capture Rate
```{r}

n_total <- nrow(data)
n_hit <- data %>%
  filter(animal != 0) %>%
  nrow()

percent_capture <- (n_hit/n_total)*100

n_total ###Total Photos
n_hit   ###Total Hits
percent_capture ### Percent Capture Rate
```
# Test Wildlife Insight App Accuracy
```{r}
WI <- read.csv("images.csv")
WI %>%
    group_by(genus) %>% filter(genus != "NA") %>%
    summarise(count=n())
head(WI)

n_total_WI <- nrow(WI)
n_hit_WI <- WI %>%
  filter(is_blank != 1) %>%   ### The WI file give blanks 1s and hits 0s
  nrow()

percent_capture_WI <- (n_hit_WI/n_total_WI)*100

n_total_WI ###Total Photos
n_hit_WI  ###Total Hits
percent_capture_WI ### Percent Capture Rate
```

